# Generated by Django 4.2.3 on 2023-08-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_process', 'In process'), ('on_pause', 'On pause'), ('close', 'Close')], default='in_process', max_length=20),
        ),
    ]
