# Generated by Django 4.2.3 on 2023-08-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In process', 'In process'), ('On pause', 'On pause'), ('Close', 'Close')], default='in_process', max_length=20),
        ),
    ]
