# Generated by Django 4.2.3 on 2023-08-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_bosstask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosstask',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bosstask',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
