# Generated by Django 4.2.3 on 2023-08-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_alter_bosstask_date_alter_bosstask_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosstask',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bosstask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
